# Default values for backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

jobs:
  - name: prometheus
    image:
      repository: ghcr.io/jaredbischof/kubernetes-file-backup
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "0.7.0"
    schedule: "* * * * *"
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    command: ["/usr/local/bin/python3", "/file_copy.py"]
    serviceAccount:
      # Specifies whether a service account should be created
      create: "true"
      # Annotations to add to the service account
      annotations: {}
    rbac: true
    rules:
    - apiGroups: [""]
      resources: ["pods/exec"]
      verbs: ["create", "get"]
