# Default values for backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/jaredbischof/kubernetes-file-backup
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.11.0"

jobs:
  - name: prometheus-5minly
    schedule: "0/5 * * * *"
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    command: ["/usr/local/bin/python3", "/prom-backup.py", "hourly", "180", "http://tartarus-prometheus.monitoring.svc.cluster.local:9090/api/v1/admin/tsdb/snapshot"]
    serviceAccount:
      # Specifies whether a service account should be created
      create: "true"
      # Annotations to add to the service account
      annotations: {}
    rbac: true
    rules:
    - apiGroups: [""]
      resources: ["pods/exec"]
      verbs: ["create", "get"]
