{{- range $job := .Values.jobs }}
{{- if and (hasKey $job "rbac") ($job.rbac) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "backup.fullname" $ }}-{{ $job.name }}
  labels:
    {{- include "backup.labels" $ | nindent 4 }}
  {{- if hasKey $job "serviceAccount.annotations" }}
  {{- with $job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- if hasKey $job "rules" }}
{{- with $job.rules }}
rules:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
