{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "backup.fullname" . }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "backup.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "backup.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
