{{- $release_namespace := .Release.Namespace }}

{{- range $job := .Values.jobs }}
{{- if and (hasKey $job "rbac") ($job.rbac) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "backup.fullname" $ }}-{{ $job.name }}
  labels:
    {{- include "backup.labels" $ | nindent 4 }}
  {{- if hasKey $job "serviceAccount.annotations" }}
  {{- with $job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "backup.fullname" $ }}-{{ $job.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "backup.fullname" $ }}-{{ $job.name }}
  namespace: {{ $release_namespace }}
{{- end }}
{{- end }}
