{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "backup.fullname" $ }}-{{ $job.name }}
  labels:
    {{- include "backup.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  schedule: {{ $job.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
        {{- if hasKey $job "serviceAccount" }}
          serviceAccountName: {{ include "backup.fullname" $ }}-{{ $job.name }}
        {{- end }}
          containers:
          - image: {{ include "backup.image.repository" }}:{{ include "backup.image.tag" }}
            imagePullPolicy: {{ include "backup.image.pullPolicy" }}
            name: {{ $job.name }}
            command:
            - /bin/sh
            - -c
            - |
              until curl -fsI http://localhost:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 3; done;
              echo \"Sidecar available. Running the command...\";
              /usr/local/bin/python3 prom-backup.py hourly 180 http://tartarus-prometheus.monitoring.svc.cluster.local:9090/api/v1/admin/tsdb/snapshot
              x=$(echo $?); curl -fsI -X POST http://localhost:15020/quitquitquit && exit $x

            {{- with $job.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          {{- with $job.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
{{- end }}
